### ISSUE TITLE
New Model - DR-HAF004S

### ISSUE THREAD

**Issue by TomWaterz** [JeffSteinbok/hass-dreo#27]
Model - DR-HAF004S
Number of speeds the fan supports: 9
Does the fan support oscilating? Yes
What preset modes are supported? Auto, Turbo, Normal, Natural, Sleep, Custom
Is temperature supported? Yes

**Comment by TomWaterz** [comment]
Tried turning on debugging and sending it commands via the app but this is all those shows up in the logs

![image](https://github.com/JeffSteinbok/hass-dreo/assets/484466/3c2c29d4-600a-4d9d-98db-eadc4882183d)

**Comment by JeffSteinbok** [comment]
How did you enable debugging?
Did you follow steps on the README ?

-Jeff

On Jul 18, 2023, at 7:07 PM, Tom Hendrick ***@***.***> wrote:

﻿

Tried turning on debugging and sending it commands via the app but this is all those shows up in the logs

[image]<https://user-images.githubusercontent.com/484466/254443520-3c2c29d4-600a-4d9d-98db-eadc4882183d.png>

**Comment by TomWaterz** [comment]
this is what my configuration.yaml looks like

![image](https://github.com/JeffSteinbok/hass-dreo/assets/484466/a7e3b363-2f11-4390-9d04-2527ddb84a69)

**Comment by JeffSteinbok** [comment]
Set them both to “debug”.

-Jeff

**Comment by TomWaterz** [comment]
added the current beta branch to my custom_components folder and I get this when trying to add the integration

![image](https://github.com/JeffSteinbok/hass-dreo/assets/484466/be56aafc-264f-477c-a8e2-5f6684332a56)

**Comment by JeffSteinbok** [comment]
Let me triple check that.  What’s the version you were using before this?

-Jeff

**Comment by JeffSteinbok** [comment]
Found the typo, sorry.
Try now.

**Comment by TomWaterz** [comment]
That fixed that and I entered my login info now getting this:

2023-07-18 22:18:31.788 DEBUG (SyncWorker_1) [pydreo] pyDreoBaseDevice:update_state: {'wifi_rssi': {'state': -32, 'timestamp': 1689726544}, 'poweron': {'state': True, 'timestamp': 1689726544}, 'cruiseconf': {'state': '90,60,0,-60', 'timestamp': 1689741652}, 'timeron': {'state': {'du': 0, 'ts': 165}, 'timestamp': None}, 'fixedconf': {'state': '0,0', 'timestamp': 1689726909}, 'mode': {'state': 3, 'timestamp': 1689743326}, 'mcuon': {'state': True, 'timestamp': 1689726544}, 'network_latency': {'state': 168, 'timestamp': 1689726544}, 'module_hardware_model': {'state': 'PAI-051', 'timestamp': 1689726544}, 'mcu_firmware_version': {'state': '0.6.3', 'timestamp': 1689726544}, 'lightsensoron': {'state': True, 'timestamp': 1689726544}, 'customconf': {'state': 'temp:22222333344455667788889', 'timestamp': 1689743312}, 'oscmode': {'state': 3, 'timestamp': 1689726960}, 'temperature': {'state': 79, 'timestamp': 1689738964}, 'module_hardware_mac': {'state': '00:1c:c2:66:c3:eb', 'timestamp': 1689726544}, 'alignon': {'state': True, 'timestamp': 1689726544}, 'muteon': {'state': True, 'timestamp': 1689743326}, 'mcu_hardware_model': {'state': 'SC95F8613B', 'timestamp': 1689726544}, 'wifi_ssid': {'state': 'Hammy', 'timestamp': 1689726544}, 'windlevel': {'state': 4, 'timestamp': 1689743356}, 'wrong': {'state': 0, 'timestamp': 1689726544}, 'module_firmware_version': {'state': '1.2.13', 'timestamp': 1689726544}, 'connected': {'state': True, 'timestamp': 1689726544}, 'timeroff': {'state': {'du': 0, 'ts': 165}, 'timestamp': None}, 'childlockon': {'state': False, 'timestamp': 1689726544}}
2023-07-18 22:18:31.788 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XXXXX@gmail.com for dreo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/__init__.py", line 37, in async_setup_entry
load_devices = await hass.async_add_executor_job(manager.load_devices)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/__init__.py", line 177, in load_devices
proc_return = self._process_devices(device_list)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/__init__.py", line 153, in _process_devices
self.load_device_state(deviceFan)
File "/config/custom_components/dreo/pydreo/__init__.py", line 204, in load_device_state
device.update_state(device_state)
File "/config/custom_components/dreo/pydreo/pydreoaircirculatorfan.py", line 73, in update_state
super().update_state(state)
File "/config/custom_components/dreo/pydreo/pydreofan.py", line 83, in update_state
self._oscillating = state[SHAKEHORIZON_KEY][STATE_KEY]
~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'shakehorizon'

**Comment by JeffSteinbok** [comment]
Wish I had one of these fans; would make life easier.
Pushed a commit to Beta – try it?

-Jeff

**Comment by TomWaterz** [comment]
same thing. heres the entire log if that helps.
```
2023-07-18 22:57:38.480 DEBUG (SyncWorker_1) [pydreo] Calling Dreo API: login
2023-07-18 22:57:38.481 DEBUG (SyncWorker_1) [pydreo] =======call_api=============================
2023-07-18 22:57:38.481 DEBUG (SyncWorker_1) [pydreo] [post] calling '/api/oauth/login' api
2023-07-18 22:57:38.481 DEBUG (SyncWorker_1) [pydreo] API call URL:
https://app-api-us.dreo-cloud.com/api/oauth/login
2023-07-18 22:57:38.481 DEBUG (SyncWorker_1) [pydreo] API call headers:
{"ua": "dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)", "lang": "en", "content-type": "application/json; charset=UTF-8", "accept-encoding": "gzip", "user-agent": "okhttp/4.9.1"}
2023-07-18 22:57:38.481 DEBUG (SyncWorker_1) [pydreo] API call json:
{"acceptLanguage": "en", "client_id": "7de37c362ee54dcf9c4561812309347a", "client_secret": "32dfa0764f25451d99f94e1693498791", "email": "##_REDACTED_##", "encrypt": "ciphertext", "grant_type": "email-password", "himei": "faede31549d649f58864093158787ec9", "password": "##_REDACTED_##", "scope": "all"}
2023-07-18 22:57:39.008 DEBUG (SyncWorker_1) [pydreo] API response:
{"code": 0, "msg": "OK", "data": {"access_token": "##_REDACTED_##", "refresh_token": "##_REDACTED_##", "countryCode": "US", "scope": "all", "token_type": "bearer", "region": "NA", "expires_in": 315344534, "userid": "1679677504773685248"}}
2023-07-18 22:57:39.008 INFO (SyncWorker_1) [pydreo] Dreo Auth reports user region as: NA
2023-07-18 22:57:39.008 DEBUG (SyncWorker_1) [pydreo] Login successful
2023-07-18 22:57:39.010 DEBUG (MainThread) [dreo] async_setup
2023-07-18 22:57:39.010 DEBUG (MainThread) [dreo] xxx@gmail.com
2023-07-18 22:57:39.010 DEBUG (SyncWorker_5) [pydreo] Calling Dreo API: login
2023-07-18 22:57:39.010 DEBUG (SyncWorker_5) [pydreo] =======call_api=============================
2023-07-18 22:57:39.010 DEBUG (SyncWorker_5) [pydreo] [post] calling '/api/oauth/login' api
2023-07-18 22:57:39.010 DEBUG (SyncWorker_5) [pydreo] API call URL:
https://app-api-us.dreo-cloud.com/api/oauth/login
2023-07-18 22:57:39.010 DEBUG (SyncWorker_5) [pydreo] API call headers:
{"ua": "dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)", "lang": "en", "content-type": "application/json; charset=UTF-8", "accept-encoding": "gzip", "user-agent": "okhttp/4.9.1"}
2023-07-18 22:57:39.010 DEBUG (SyncWorker_5) [pydreo] API call json:
{"acceptLanguage": "en", "client_id": "7de37c362ee54dcf9c4561812309347a", "client_secret": "32dfa0764f25451d99f94e1693498791", "email": "##_REDACTED_##", "encrypt": "ciphertext", "grant_type": "email-password", "himei": "faede31549d649f58864093158787ec9", "password": "##_REDACTED_##", "scope": "all"}
2023-07-18 22:57:39.502 DEBUG (SyncWorker_5) [pydreo] API response:
{"code": 0, "msg": "OK", "data": {"access_token": "##_REDACTED_##", "refresh_token": "##_REDACTED_##", "countryCode": "US", "scope": "all", "token_type": "bearer", "region": "NA", "expires_in": 315344533, "userid": "1679677504773685248"}}
2023-07-18 22:57:39.502 INFO (SyncWorker_5) [pydreo] Dreo Auth reports user region as: NA
2023-07-18 22:57:39.502 DEBUG (SyncWorker_5) [pydreo] Login successful
2023-07-18 22:57:39.503 DEBUG (SyncWorker_0) [pydreo] Calling Dreo API: devicelist
2023-07-18 22:57:39.503 DEBUG (SyncWorker_0) [pydreo] =======call_api=============================
2023-07-18 22:57:39.503 DEBUG (SyncWorker_0) [pydreo] [get] calling '/api/v2/user-device/device/list' api
2023-07-18 22:57:39.503 DEBUG (SyncWorker_0) [pydreo] API call URL:
https://app-api-us.dreo-cloud.com/api/v2/user-device/device/list
2023-07-18 22:57:39.503 DEBUG (SyncWorker_0) [pydreo] API call headers:
{"ua": "dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)", "lang": "en", "content-type": "application/json; charset=UTF-8", "accept-encoding": "gzip", "user-agent": "okhttp/4.9.1", "authorization": "Bearer 900ac3c7-5308-4d5e-b4bd-8fd5a7ce4a27"}
2023-07-18 22:57:39.503 DEBUG (SyncWorker_0) [pydreo] API call json:
{"acceptLanguage": "en", "method": "devices", "pageNo": "1", "pageSize": "100"}
2023-07-18 22:57:39.917 DEBUG (SyncWorker_0) [pydreo] API response:
{"code": 0, "msg": "OK", "data": {"currentPage": 1, "pageSize": 100, "totalNum": 1, "totalPage": 1, "list": [{"deviceId": "1681461090766032898", "sn": "1572127914365333506-992e857305ed738:001:0000000000s", "brand": "Dreo", "model": "DR-HAF004S", "productId": "1572127914365333506", "productName": "Air Circulator", "deviceName": "BLOWHARD", "shared": false, "series": null, "seriesName": "CF714S", "controlsConf": {"template": "DR-HAF004S", "lottie": {"key": "poweron", "frames": [{"value": 0, "frame": [0]}, {"value": 1, "frame": [2]}]}, "cards": [{"type": 2, "title": "device_control_temp", "icon": "", "image": "", "url": "", "show": true}, {"type": 6, "title": "device_settings_title", "icon": "ic_setting", "image": "", "url": "dreo://nav/device/setting?deviceSn=${sn}", "show": true, "key": "setting"}], "preference": [{"id": "200", "type": "Panel Sound", "title": "device_control_panelsound", "image": "ic_mute", "reverse": true, "cmd": "muteon"}, {"id": "210", "type": "Light Detection", "title": "device_control_lightdetection", "image": "ic_lightsensoron", "reverse": false, "cmd": "lightsensoron"}, {"id": "220", "type": "Child Lock", "title": "device_control_childlock", "image": "ic_child_lock", "reverse": false, "cmd": "childlockon"}, {"id": "230", "type": "Oscillation Calibration", "title": "device_control_calibration", "image": "ic_osc_cal"}, {"id": "240", "type": "Temperature Unit", "title": "device_control_temp_unit", "image": "ic_temp_unit"}], "control": [{"id": "100", "type": "Mode", "title": "device_mode", "items": [{"text": "device_fans_mode_straight", "textColors": ["#D5D6D7", "#D5D6D7"], "image": "ic_normal_wind", "imageColors": ["#D5D6D7", "#25D7E4"], "cmd": "mode", "value": 1}, {"text": "device_fans_mode_natural", "textColors": ["#D5D6D7", "#D5D6D7"], "image": "ic_natural_wind", "imageColors": ["#D5D6D7", "#2CDD96"], "cmd": "mode", "value": 2}, {"text": "device_control_mode_sleep", "textColors": ["#D5D6D7", "#D5D6D7"], "image": "ic_sleep_wind", "imageColors": ["#D5D6D7", "#6249DF"], "cmd": "mode", "value": 3}, {"text": "device_control_mode_auto", "textColors": ["#D5D6D7", "#D5D6D7"], "image": "ic_auto_wind", "imageColors": ["#D5D6D7", "#0A80F5"], "cmd": "mode", "value": 4}]}, {"id": "110", "type": "Speed", "title": "device_control_speed", "items": [{"text": "1", "cmd": "windlevel", "value": 1}, {"text": "9", "cmd": "windlevel", "value": 9}]}, {"id": "130", "type": "DPad", "step": 5}], "category": "Air Circulators", "version": {"minControlVer": "2.0.7", "minPairingVer": "2.0.7"}, "updateMcuVersion": ""}, "mainConf": {"isSmart": true, "isWifi": true, "isBluetooth": true, "isVoiceControl": true}, "resourcesConf": {"imageSmallSrc": "https://resources.dreo-cloud.com/app/202302/15b4a846f9849144729e6d3a9fe6592d95.png", "imageFullSrc": "https://resources.dreo-cloud.com/app/202302/158b6be82ae48e45fbb41e8d73af5e32e8.zip"}, "servicesConf": [{"key": "user_manual", "value": "https://resources.dreo-cloud.com/app/202302/15dd1913e68d1148188a8bf366feb0fd2f.pdf"}]}]}}
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] pydreo._process_devices
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] New device list initialized
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] found device with model DR-HAF004S
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] DR-HAF004S is an air circulator
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] load_device_state
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] Calling Dreo API: devicestate
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] =======call_api=============================
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] [get] calling '/api/user-device/device/state' api
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] API call URL:
https://app-api-us.dreo-cloud.com/api/user-device/device/state
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] API call headers:
{"ua": "dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)", "lang": "en", "content-type": "application/json; charset=UTF-8", "accept-encoding": "gzip", "user-agent": "okhttp/4.9.1", "authorization": "Bearer 900ac3c7-5308-4d5e-b4bd-8fd5a7ce4a27"}
2023-07-18 22:57:39.918 DEBUG (SyncWorker_0) [pydreo] API call json:
{"deviceSn": "1572127914365333506-992e857305ed738:001:0000000000s"}
2023-07-18 22:57:40.280 DEBUG (SyncWorker_0) [pydreo] API response:
{"code": 0, "msg": "OK", "data": {"mixed": {"wifi_rssi": {"state": -32, "timestamp": 1689726544}, "poweron": {"state": true, "timestamp": 1689726544}, "cruiseconf": {"state": "90,60,0,-60", "timestamp": 1689741652}, "timeron": {"state": {"du": 0, "ts": 165}, "timestamp": null}, "fixedconf": {"state": "0,0", "timestamp": 1689744422}, "mode": {"state": 3, "timestamp": 1689744472}, "mcuon": {"state": true, "timestamp": 1689726544}, "network_latency": {"state": 168, "timestamp": 1689726544}, "module_hardware_model": {"state": "PAI-051", "timestamp": 1689726544}, "mcu_firmware_version": {"state": "0.6.3", "timestamp": 1689726544}, "lightsensoron": {"state": true, "timestamp": 1689726544}, "customconf": {"state": "temp:22222333344455667788889", "timestamp": 1689743312}, "oscmode": {"state": 3, "timestamp": 1689744458}, "temperature": {"state": 79, "timestamp": 1689745312}, "module_hardware_mac": {"state": "00:1c:c2:66:c3:eb", "timestamp": 1689726544}, "alignon": {"state": true, "timestamp": 1689726544}, "muteon": {"state": true, "timestamp": 1689744472}, "mcu_hardware_model": {"state": "SC95F8613B", "timestamp": 1689726544}, "wifi_ssid": {"state": "Hammy", "timestamp": 1689726544}, "windlevel": {"state": 5, "timestamp": 1689744470}, "wrong": {"state": 0, "timestamp": 1689726544}, "module_firmware_version": {"state": "1.2.13", "timestamp": 1689726544}, "connected": {"state": true, "timestamp": 1689726544}, "timeroff": {"state": {"du": 0, "ts": 165}, "timestamp": null}, "childlockon": {"state": false, "timestamp": 1689726544}}, "sn": "1572127914365333506-992e857305ed738:001:0000000000s", "productId": "1572127914365333506", "region": "us-east-2"}}
2023-07-18 22:57:40.281 DEBUG (SyncWorker_0) [pydreo] PyDreoAirCirculatorFan:update_state
2023-07-18 22:57:40.281 DEBUG (SyncWorker_0) [pydreo] PyDreoFan:update_state
2023-07-18 22:57:40.281 DEBUG (SyncWorker_0) [pydreo] pyDreoBaseDevice:update_state: {'wifi_rssi': {'state': -32, 'timestamp': 1689726544}, 'poweron': {'state': True, 'timestamp': 1689726544}, 'cruiseconf': {'state': '90,60,0,-60', 'timestamp': 1689741652}, 'timeron': {'state': {'du': 0, 'ts': 165}, 'timestamp': None}, 'fixedconf': {'state': '0,0', 'timestamp': 1689744422}, 'mode': {'state': 3, 'timestamp': 1689744472}, 'mcuon': {'state': True, 'timestamp': 1689726544}, 'network_latency': {'state': 168, 'timestamp': 1689726544}, 'module_hardware_model': {'state': 'PAI-051', 'timestamp': 1689726544}, 'mcu_firmware_version': {'state': '0.6.3', 'timestamp': 1689726544}, 'lightsensoron': {'state': True, 'timestamp': 1689726544}, 'customconf': {'state': 'temp:22222333344455667788889', 'timestamp': 1689743312}, 'oscmode': {'state': 3, 'timestamp': 1689744458}, 'temperature': {'state': 79, 'timestamp': 1689745312}, 'module_hardware_mac': {'state': '00:1c:c2:66:c3:eb', 'timestamp': 1689726544}, 'alignon': {'state': True, 'timestamp': 1689726544}, 'muteon': {'state': True, 'timestamp': 1689744472}, 'mcu_hardware_model': {'state': 'SC95F8613B', 'timestamp': 1689726544}, 'wifi_ssid': {'state': 'Hammy', 'timestamp': 1689726544}, 'windlevel': {'state': 5, 'timestamp': 1689744470}, 'wrong': {'state': 0, 'timestamp': 1689726544}, 'module_firmware_version': {'state': '1.2.13', 'timestamp': 1689726544}, 'connected': {'state': True, 'timestamp': 1689726544}, 'timeroff': {'state': {'du': 0, 'ts': 165}, 'timestamp': None}, 'childlockon': {'state': False, 'timestamp': 1689726544}}
2023-07-18 22:57:40.282 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@gmail.com for dreo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/__init__.py", line 37, in async_setup_entry
load_devices = await hass.async_add_executor_job(manager.load_devices)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/__init__.py", line 177, in load_devices
proc_return = self._process_devices(device_list)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/__init__.py", line 153, in _process_devices
self.load_device_state(deviceFan)
File "/config/custom_components/dreo/pydreo/__init__.py", line 204, in load_device_state
device.update_state(device_state)
File "/config/custom_components/dreo/pydreo/pydreoaircirculatorfan.py", line 73, in update_state
super().update_state(state)
File "/config/custom_components/dreo/pydreo/pydreofan.py", line 83, in update_state
self._oscillating = state[SHAKEHORIZON_KEY][STATE_KEY]
~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'shakehorizon'
```

**Comment by JeffSteinbok** [comment]
Sorry, the commit didn’t push…
Try now

-Jeff

**Comment by TomWaterz** [comment]
```
2023-07-18 23:13:16.251 DEBUG (SyncWorker_2) [pydreo] pyDreoBaseDevice:update_state: {'wifi_rssi': {'state': -32, 'timestamp': 1689726544}, 'poweron': {'state': True, 'timestamp': 1689726544}, 'cruiseconf': {'state': '90,60,0,-60', 'timestamp': 1689741652}, 'timeron': {'state': {'du': 0, 'ts': 165}, 'timestamp': None}, 'fixedconf': {'state': '0,0', 'timestamp': 1689744422}, 'mode': {'state': 3, 'timestamp': 1689744472}, 'mcuon': {'state': True, 'timestamp': 1689726544}, 'network_latency': {'state': 168, 'timestamp': 1689726544}, 'module_hardware_model': {'state': 'PAI-051', 'timestamp': 1689726544}, 'mcu_firmware_version': {'state': '0.6.3', 'timestamp': 1689726544}, 'lightsensoron': {'state': True, 'timestamp': 1689726544}, 'customconf': {'state': 'temp:22222333344455667788889', 'timestamp': 1689743312}, 'oscmode': {'state': 3, 'timestamp': 1689744458}, 'temperature': {'state': 78, 'timestamp': 1689746968}, 'module_hardware_mac': {'state': '00:1c:c2:66:c3:eb', 'timestamp': 1689726544}, 'alignon': {'state': True, 'timestamp': 1689726544}, 'muteon': {'state': True, 'timestamp': 1689744472}, 'mcu_hardware_model': {'state': 'SC95F8613B', 'timestamp': 1689726544}, 'wifi_ssid': {'state': 'Hammy', 'timestamp': 1689726544}, 'windlevel': {'state': 4, 'timestamp': 1689746617}, 'wrong': {'state': 0, 'timestamp': 1689726544}, 'module_firmware_version': {'state': '1.2.13', 'timestamp': 1689726544}, 'connected': {'state': True, 'timestamp': 1689726544}, 'timeroff': {'state': {'du': 0, 'ts': 165}, 'timestamp': None}, 'childlockon': {'state': False, 'timestamp': 1689726544}}
2023-07-18 23:13:16.251 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@gmail.com for dreo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/__init__.py", line 37, in async_setup_entry
load_devices = await hass.async_add_executor_job(manager.load_devices)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/__init__.py", line 177, in load_devices
proc_return = self._process_devices(device_list)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/__init__.py", line 153, in _process_devices
self.load_device_state(deviceFan)
File "/config/custom_components/dreo/pydreo/__init__.py", line 204, in load_device_state
device.update_state(device_state)
File "/config/custom_components/dreo/pydreo/pydreoaircirculatorfan.py", line 78, in update_state
self._horizontally_oscillating = self.get_state_update_value(state, HORIZONTAL_OSCILLATION_KEY)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/pydreo/pydreobasedevice.py", line 66, in get_state_update_value
keyValObject: dict = state[key]
~~~~~^^^^^
KeyError: 'hoscon'
```

**Comment by JeffSteinbok** [comment]
Love debugging like this.
Updated Beta – and tested the method this time. 😊

-Jeff

**Comment by TomWaterz** [comment]
seems to be working now. great job. obviously the UI in HA only has the speed and mode stuff but everything seems to be good now. Thanks

**Comment by JeffSteinbok** [comment]
Yes, the UX is the Fan Entity UX that HA provides.  I'm planning on adding additional attributes/sensors/switches to allow you to change the non-standard stuff, and someone could write a custom LoveLace card to expose.
