### ISSUE TITLE
Websocket Closing

### ISSUE THREAD

**Issue by lukas-clarke** [JeffSteinbok/hass-dreo#33]
The websocket for my HASS Dreo integration would close. Since there is no error handling for this, the device would remain available like it works, but would no longer update state or send commands.

My fix for this is to add a try, except clause in the send_command and _ws_ping_handler method that catch a ConnectionClosedOK error. And when/if this error is caught, the websocket is repopened and initialized by calling self.start_monitoring()

**Comment by JeffSteinbok** [comment]
Latest version SHOULD detect and re-connect.
Try it out?

From: lukas-clarke ***@***.***>
Sent: Wednesday, July 19, 2023 12:30 PM
To: JeffSteinbok/hass-dreo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JeffSteinbok/hass-dreo] Websocket Closing (Issue #33)


The websocket for my HASS Dreo integration would close. Since there is no error handling for this, the device would remain available like it works, but would no longer update state or send commands.

My fix for this is to add a try, except clause in the send_command and _ws_ping_handler method that catch a ConnectionClosedOK error. And when/if this error is caught, the websocket is repopened and initialized by calling self.start_monitoring()

-

**Comment by lukas-clarke** [comment]
Oh, did not expect you to get to this so fast. I made a PR with my changes, and I'll check out the latest release to see if it works for me.

**Comment by Maksim-us** [comment]
I know this is closed, but running the latest version (v0.4.1), after not using the fan for a while, it seems to loose connection. Getting `Failed to call service fan/turn_on. connection lost`.
<details><summary>HA Log</summary>

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dreo/pydreo/__init__.py:357
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:04:19 (10 occurrences)
Last logged: 10:08:22

[1369339312] no close frame received or sent
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 727, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 275, in async_turn_on
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/fan.py", line 108, in turn_on
    self.device.is_on = True
    ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/pydreofan.py", line 62, in is_on
    self._send_command(POWERON_KEY, value)
  File "/config/custom_components/dreo/pydreo/pydreobasedevice.py", line 74, in _send_command
    self._dreo.send_command(self, params)
  File "/config/custom_components/dreo/pydreo/__init__.py", line 357, in send_command
    asyncio.run(self.ws.send(content))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
</details>

**Comment by JeffSteinbok** [comment]
I'm re-opening this issue.  Python is still new to me, and I'm clearly not detecting it right.  Even if you don't use it, the add-in pings the server every so often to keep the connection alive.

**Comment by jt6186** [comment]
> I know this is closed, but running the latest version (v0.4.1), after not using the fan for a while, it seems to loose connection. Getting `Failed to call service fan/turn_on. connection lost`.
> 
> HA Log

I'm getting the same error message, have been for a few weeks at least.  My log is slightly different.
[HA Log.txt](https://github.com/JeffSteinbok/hass-dreo/files/12402145/HA.Log.txt)

**Comment by JeffSteinbok** [comment]
Are you able to test a private branch? 
Will involve manually installing.  Let me know.  If so, try this out: 
https://github.com/JeffSteinbok/hass-dreo/tree/infra/websocketreconnect2

**Comment by lukas-clarke** [comment]
Yup, I can take a look.
Super busy at work this week, so it will have to wait until the weekend
though.

**Comment by Maksim-us** [comment]
Do I need to remove the regular one?

**Comment by JeffSteinbok** [comment]
No, overwrite.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Maksim-us** [comment]
Copied the dreo directory form the websocketreconnect2 branch over my current dreo directory in custom_components and restarted HA. Seem to work. I guess we'll see what happens after some time. Thanks!

**Comment by miggi92** [comment]
> Copied the dreo directory form the websocketreconnect2 branch over my current dreo directory in custom_components and restarted HA. Seem to work. I guess we'll see what happens after some time. Thanks!

for me this worked, too.

**Comment by JeffSteinbok** [comment]
Pushed v0.6
