### ISSUE TITLE
Add Support for DR-HSH009AS

### ISSUE THREAD

**Issue by ptmgcorp** [JeffSteinbok/hass-dreo#74]
You already have a DR-HSH009S supported the DR-HSH009AS is identical, just the plug is different which has a ALCI Safety Plug. The rest is all the same.

Model: DR-HSH009AS
Number of Speeds: No speeds
Does the fan support oscillating: Yes, can oscillate in 3 positions pointing to floor / mid / ceiling and auto
What preset modes are supported: H1, H2, H3, and Eco mode which can be set to a specific temperature.
Is temperature supported: yes when in Eco Mode.

![Screenshot_20240312-180303](https://github.com/JeffSteinbok/hass-dreo/assets/116841927/c7be85c2-80fe-4393-8e5b-f920522fec9b)

**Comment by ptmgcorp** [comment]
For those who has the DR-HSH009AS with the ALCI Safety Plug, Downloading the main branch will get it to work. It appears as a DR-HSH009S even though its a DR-HSH009AS. Just that the climate domain wont load because of an error in the climate.py file in the dreo custom component folder.

Here is the error:
```
2024-03-16 15:17:57.752 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform dreo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
capabilities=entity.capability_attributes,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 276, in capability_attributes
supported_features = self.supported_features
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/climate.py", line 202, in supported_features
supported_features |= ClimateEntityFeature.TURN_OFF
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
raise AttributeError(name) from None
AttributeError: TURN_OFF
2024-03-16 15:17:57.800 ERROR (MainThread) [homeassistant.components.climate] Error while setting up dreo platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
capabilities=entity.capability_attributes,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 276, in capability_attributes
supported_features = self.supported_features
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreo/climate.py", line 202, in supported_features
supported_features |= ClimateEntityFeature.TURN_OFF
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
raise AttributeError(name) from None
AttributeError: TURN_OFF
```

I just comment this section in the climate.py restart HA and it works. 
```
        # if self.device.poweron is not None:
        #     supported_features |= ClimateEntityFeature.TURN_OFF
        #     supported_features |= ClimateEntityFeature.TURN_ON
```
But its missing the osc mode on the climate card.

**Comment by JeffSteinbok** [comment]
@andy-cooper did you want to look at this?

**Comment by JeffSteinbok** [comment]
Should be in there
