### ISSUE TITLE
Turning fan on/off is not working 

### ISSUE THREAD

**Issue by khushalkumthekar** [JeffSteinbok/hass-dreo#97]
I have 2 dreo fans (Tower fan DR-HTF004s and Pedestal Fan DR-HAF003S). I added both to HA and was able to turn them on and off using the integration. But now its not working for both the fans. When i try to turn them on or off using the power button in the integration nothing happens (essentially the state does not change). I enabled the debug logging and see below in the log

2024-05-12 14:44:49.014 WARNING (DreoWebSocketStream) [homeassistant.helpers.frame] Detected that custom integration 'dreo' calls async_create_task from a thread at custom_components/dreo/basedevice.py, line 53: self.async_schedule_update_ha_state(True), please report it to the author of the 'dreo' custom integration
2024-05-12 14:44:49.015 ERROR (DreoWebSocketStream) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/dreo/pydreo/commandtransport.py", line 129, in _ws_consumer_handler
self._ws_consume_message(json.loads(message))
File "/config/custom_components/dreo/pydreo/commandtransport.py", line 161, in _ws_consume_message
self._recv_callback(message)
File "/config/custom_components/dreo/pydreo/__init__.py", line 324, in _transport_consume_message
device.handle_server_update_base(message)
File "/config/custom_components/dreo/pydreo/pydreobasedevice.py", line 79, in handle_server_update_base
self._do_callbacks()
File "/config/custom_components/dreo/pydreo/pydreobasedevice.py", line 117, in _do_callbacks
cb()
File "/config/custom_components/dreo/basedevice.py", line 53, in update_state
self.async_schedule_update_ha_state(True)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1252, in async_schedule_update_ha_state
self.hass.async_create_task(
File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
self.verify_event_loop_thread("async_create_task")
File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
frame.report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
_report_integration(what, integration_frame, level, error_if_integration)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
raise RuntimeError(
RuntimeError: Detected that custom integration 'dreo' calls async_create_task from a thread at custom_components/dreo/basedevice.py, line 53: self.async_schedule_update_ha_state(True). Please report it to the author of the 'dreo' custom integration.
2024-05-12 14:44:49.023 WARNING (DreoWebSocketStream) [py.warnings] /config/custom_components/dreo/pydreo/commandtransport.py:101: RuntimeWarning: coroutine 'Entity.async_update_ha_state' was never awaited
await self._ws_handler(ws)
2024-05-12 14:45:05.524 WARNING (DreoWebSocketStream) [homeassistant.helpers.frame] Detected that custom integration 'dreo' calls async_create_task from a thread at custom_components/dreo/basedevice.py, line 53: self.async_schedule_update_ha_state(True), please report it to the author of the 'dreo' custom integration

**Comment by khushalkumthekar** [comment]
This was actually fixed in v 0.6.4. If anyone else runs into similar issue just update your integration in HACS to 0.6.4 or later.
